apiVersion: v1
kind: Pod
metadata:
  name: localization-api1
  labels:
    app: localization-api
    version: v1
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
    cluster: rasp1
  containers:
    - name: localization-api
      image: wrathchild14/localization-reg:latest
      resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
      resources:
        limits:
          cpu: "500m"
          memory: 2Gi
      ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Pod
metadata:
  name: localization-api2
  labels:
    app: localization-api
    version: v2
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
    cluster: rasp2
  containers:
    - name: localization-api
      image: wrathchild14/localization-reg:latest
      resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
      resources:
        limits:
          cpu: "500m"
          memory: 2Gi
      ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Pod
metadata:
  name: localization-api3
  labels:
    app: localization-api
    version: v3
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
    cluster: rasp1
  containers:
    - name: localization-api
      image: wrathchild14/localization-reg:latest
      resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
      resources:
        limits:
          cpu: "500m"
          memory: 2Gi
      ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: localization-service1
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8000
  selector:
    app: localization-api
    version: v1

---

apiVersion: v1
kind: Service
metadata:
  name: localization-service2
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8000
  selector:
    app: localization-api
    version: v2

---

apiVersion: v1
kind: Service
metadata:
  name: localization-service3
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8000
  selector:
    app: localization-api
    version: v3

---

# All this stuff to rewrite /api1, /api2, /api3 to / and keep the /predict...
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localization-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /api1/(.*)
        backend:
          service:
            name: localization-service1
            port:
              number: 8081
      - pathType: ImplementationSpecific
        path: /api2/(.*)
        backend:
          service:
            name: localization-service2
            port:
              number: 8082
      - pathType: ImplementationSpecific
        path: /api3/(.*)
        backend:
          service:
            name: localization-service3
            port:
              number: 8083