---
apiVersion: v1
kind: Pod
metadata:
  name: ray-worker-pod-rasp1
  labels:
    component: ray-worker
    type: ray
    app: ray-cluster-worker
spec:
  nodeSelector:
    cluster: rasp1
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    - name: ray-worker
      #      image: wrathchild14/raspray:arm64
      image: rayproject/ray:2.9.0-py310-cpu-aarch64
      resizePolicy:
      - resourceName: cpu
        restartPolicy: NotRequired
      - resourceName: memory
        restartPolicy: NotRequired
      resources:
        limits:
          cpu: "500m"
          memory: 2Gi
        requests:
          cpu: "500m"
          memory: 1Gi
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args:
        - "ray start --num-cpus=4 --address=service-ray-cluster:6380 --object-manager-port=8076 --node-manager-port=8077 --dashboard-agent-grpc-port=8078 --dashboard-agent-listen-port=52365 --block"
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
---
apiVersion: v1
kind: Pod
metadata:
  name: ray-worker-pod-rasp2
  labels:
    component: ray-worker
    type: ray
    app: ray-cluster-worker
spec:
  nodeSelector:
    cluster: rasp2
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    - name: ray-worker
      #      image: wrathchild14/raspray:arm64
      image: rayproject/ray:2.9.0-py310-cpu-aarch64
      resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
      resources:
        limits:
          cpu: "500m"
          memory: 2Gi
        requests:
          cpu: "500m"
          memory: 1Gi
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args:
        - "ray start --num-cpus=4 --address=service-ray-cluster:6380 --object-manager-port=8076 --node-manager-port=8077 --dashboard-agent-grpc-port=8078 --dashboard-agent-listen-port=52365 --block"
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm