apiVersion: v1
kind: Pod
metadata:
  name: nvg-api1
  labels:
    app: nvg-api
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
    cluster: rasp1
  containers:
    - name: nvg-api
      image: wrathchild14/api-nvg:multiarch
      resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
      resources:
        limits:
          cpu: "2"
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nvg-service
spec:
  type: LoadBalancer
  ports:
    - port: 8088
      targetPort: 8000
  selector:
    app: nvg-api
  externalTrafficPolicy: Local
