apiVersion: v1
kind: Pod
metadata:
  name: nvg-api1
  labels:
    app: nvg-api
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
    cluster: rasp1
  containers:
    - name: nvg-api
      image: wrathchild14/api-nvg:multiarch
      resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nvg-service
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8000
  selector:
    app: nvg-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nvg-api-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nvg-service
            port:
              number: 8088
