apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        cluster: vm
      containers:
      - name: frontend
        image: wrathchild14/marlise-frontend:latest
        ports:
        - containerPort: 84
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 84
      targetPort: 84
      nodePort: 30000
  type: NodePort
