apiVersion: apps/v1
kind: Deployment
metadata:
  name: localization-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localization-api
  template:
    metadata:
      labels:
        app: localization-api
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: localization-api
        image: wrathchild14/localization-reg:latest
        resources:
          limits:
            cpu: "200m"
            memory: 600Mi
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: localization-service
  namespace: default
spec:
  selector:
    app: localization-api
  ports:
    - port: 8088
      targetPort: 8000
  type: ClusterIP


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localization-ingress
  namespace: default
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: localization-service
            port:
              number: 8088

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: localization-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: localization-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
