name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/docker-image.yml'
      - 'configs/elasticity_config.yaml'
      - 'trained/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/docker-image.yml'
      - 'configs/elasticity_config.yaml'
      - 'trained/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Multi-Arch Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/Dockerfile
        push: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        platforms: linux/amd64,linux/arm64
        tags: |
          wrathchild14/elasticity:latest
          wrathchild14/elasticity:${{ github.sha }}
          wrathchild14/elasticity:${{ github.ref_name }}
